FROM node:20.17.0 AS dependencies
WORKDIR /dependencies
COPY package*.json ./
ENV NODE_ENV=development
RUN npm install --verbose

FROM node:20.17.0 AS api
WORKDIR /usr/src/app
COPY . . 
COPY --from=dependencies /dependencies/node_modules ./node_modules

EXPOSE ${APP_PORT}  
CMD ["sh", "-c", "npm run start:dev"]






