services:
  database:
    image: postgres:17.0-alpine
    container_name: rdmovies-postgres
    ports:
      - ${DATABASE_PORT}:5432
    volumes:
      - rdmovies-db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    networks:
      - rdmovies-network

  api:
    build:
      context: .
      dockerfile: Dockerfile-prod
    container_name: rdmovies-api
    ports:
      - ${APP_PORT}:${APP_PORT}
    networks:
      - rdmovies-network

networks:
  rdmovies-network:
    driver: bridge
volumes:
  rdmovies-db:
